### ISSUE TITLE
First glitch: I had no write access to `/tmp/fractal_test/`, and then I had to enter the container to download images.

### ISSUE THREAD

**Issue by tcompa** [exactlab/fractal-containers#10]
First glitch: I had no write access to `/tmp/fractal_test/`, and then I had to enter the container to download images.

_Originally posted by @tcompa in https://github.com/exactlab/fractal-containers/issues/9#issuecomment-1705221584_

**Comment by tcompa** [comment]
I see two ways out:
1. We provide 777 permissions to that folder: would it work both ways? Would files from host-machine user be readable from the container?
2. We incorporate point 2 from https://github.com/exactlab/fractal-containers/issues/9#issuecomment-1705249066 into the Dockerfile, with a small script.

**Comment by aangelone2** [comment]
The current solution is to use for data exchange the `fractal-data/` folder, automatically created by the host when running `make run` (before the first execution of the containers).

This folder is mapped to `/home/fractal-data/` on the container filesystem, and allows writing and reading of all contained files from both sides (from the host user due to ownership, and from the container due to `root`'s superior permissions).
